"""pin conversations

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 01:12:27.943139
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_members', 'pinned_at')
    # ### end Alembic commands ###
