"""expenses and receipt scanning

Expenses, payers, shares, history, settlements, receipts read by AI, store discounts,
AI model settings. Seeds the default receipt-scanning models and the monthly scan limit.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 12:09:58.400750
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('store_discount_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=80), nullable=False),
    sa.Column('store_key', sa.String(length=60), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('excluded_categories', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('stacks_with_reduced', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_discount_rules_owner_id'), 'store_discount_rules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_store_discount_rules_store_key'), 'store_discount_rules', ['store_key'], unique=False)
    op.create_table('user_ai_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_model_id', sa.Integer(), nullable=True),
    sa.Column('anthropic_key_encrypted', sa.Text(), nullable=True),
    sa.Column('openai_key_encrypted', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('conversation_settings',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('simplify_debts', sa.Boolean(), nullable=False),
    sa.Column('receipt_model_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('item_preferences',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=False),
    sa.Column('user_ids', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'item_key')
    )
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('key_source', sa.String(length=10), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('store_key', sa.String(length=60), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('printed_total_minor', sa.BigInteger(), nullable=True),
    sa.Column('prices_include_tax', sa.Boolean(), nullable=False),
    sa.Column('warnings', postgresql.ARRAY(sa.String(length=300)), nullable=False),
    sa.Column('payers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_conversation_id'), 'receipts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_receipts_uploaded_by'), 'receipts', ['uploaded_by'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('from_user', sa.UUID(), nullable=False),
    sa.Column('to_user', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_conversation_id'), 'settlements', ['conversation_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('split_mode', sa.String(length=10), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('spent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expense_conversation_spent', 'expenses', ['conversation_id', 'spent_at'], unique=False)
    op.create_index(op.f('ix_expenses_conversation_id'), 'expenses', ['conversation_id'], unique=False)
    op.create_table('receipt_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('item_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('allocation', sa.String(length=15), nullable=False),
    sa.Column('assignee_ids', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_adjustments_receipt_id'), 'receipt_adjustments', ['receipt_id'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('tax_code', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('split_mode', sa.String(length=10), nullable=False),
    sa.Column('assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_suggestion_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    op.create_table('expense_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_events_expense_id'), 'expense_events', ['expense_id'], unique=False)
    op.create_table('expense_payers',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', 'user_id')
    )
    op.create_table('expense_shares',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('split_value', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', 'user_id')
    )
    op.add_column('messages', sa.Column('expense_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_messages_expense_id', 'messages', 'expenses', ['expense_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_app_admin', sa.Boolean(), server_default='false', nullable=False))

    # Receipt-scanning models available out of the box (app admins can change these in the app)
    ai_models = sa.table(
        'ai_models',
        sa.column('provider', sa.String), sa.column('model_id', sa.String), sa.column('label', sa.String),
        sa.column('description', sa.String), sa.column('enabled', sa.Boolean),
        sa.column('is_default', sa.Boolean), sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(ai_models, [
        {'provider': 'anthropic', 'model_id': 'claude-opus-5', 'label': 'Most accurate (Claude Opus 5)',
         'description': 'Best for long or messy receipts', 'enabled': True, 'is_default': True, 'sort_order': 1},
        {'provider': 'anthropic', 'model_id': 'claude-sonnet-5', 'label': 'Balanced (Claude Sonnet 5)',
         'description': 'Good accuracy at lower cost', 'enabled': True, 'is_default': False, 'sort_order': 2},
        {'provider': 'anthropic', 'model_id': 'claude-haiku-4-5', 'label': 'Cheapest (Claude Haiku 4.5)',
         'description': 'Fast and low cost; best for clear receipts', 'enabled': True, 'is_default': False, 'sort_order': 3},
    ])
    app_settings = sa.table('app_settings', sa.column('key', sa.String), sa.column('value', sa.String))
    op.bulk_insert(app_settings, [{'key': 'receipt_scans_per_month', 'value': '50'}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_app_admin')
    op.drop_constraint('fk_messages_expense_id', 'messages', type_='foreignkey')
    op.drop_column('messages', 'expense_id')
    op.drop_table('expense_shares')
    op.drop_table('expense_payers')
    op.drop_index(op.f('ix_expense_events_expense_id'), table_name='expense_events')
    op.drop_table('expense_events')
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipt_adjustments_receipt_id'), table_name='receipt_adjustments')
    op.drop_table('receipt_adjustments')
    op.drop_index(op.f('ix_expenses_conversation_id'), table_name='expenses')
    op.drop_index('idx_expense_conversation_spent', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_settlements_conversation_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_receipts_uploaded_by'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_conversation_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_table('item_preferences')
    op.drop_table('conversation_settings')
    op.drop_table('user_ai_settings')
    op.drop_index(op.f('ix_store_discount_rules_store_key'), table_name='store_discount_rules')
    op.drop_index(op.f('ix_store_discount_rules_owner_id'), table_name='store_discount_rules')
    op.drop_table('store_discount_rules')
    op.drop_table('app_settings')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
