"""email verification codes (existing accounts count as verified)

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 15:29:12.521782
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_code_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_code_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_code_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # People who signed up before codes existed keep working
    op.execute("UPDATE users SET email_verified = true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_code_attempts')
    op.drop_column('users', 'email_code_sent_at')
    op.drop_column('users', 'email_code_expires')
    op.drop_column('users', 'email_code_hash')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
