"""e2e v2 devices prekeys mailboxes

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-08 16:20:05.827485
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e2e_device_lists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('aik', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('signed_list', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('e2e_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sign_public', sa.String(length=64), nullable=False),
    sa.Column('dh_public', sa.String(length=64), nullable=False),
    sa.Column('dh_signature', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id')
    )
    op.create_index(op.f('ix_e2e_devices_user_id'), 'e2e_devices', ['user_id'], unique=False)
    op.create_table('e2e_link_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ephemeral_public', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('grant', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e2e_link_requests_code'), 'e2e_link_requests', ['code'], unique=False)
    op.create_index(op.f('ix_e2e_link_requests_user_id'), 'e2e_link_requests', ['user_id'], unique=False)
    op.create_table('e2e_one_time_prekeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'key_id')
    )
    op.create_index('ix_e2e_otpk_device', 'e2e_one_time_prekeys', ['user_id', 'device_id'], unique=False)
    op.create_table('e2e_signed_prekeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'key_id')
    )
    op.create_table('e2e_envelopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_device_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('sender_device_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('packet', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_e2e_envelope_recipient', 'e2e_envelopes', ['recipient_user_id', 'recipient_device_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_e2e_envelope_recipient', table_name='e2e_envelopes')
    op.drop_table('e2e_envelopes')
    op.drop_table('e2e_signed_prekeys')
    op.drop_index('ix_e2e_otpk_device', table_name='e2e_one_time_prekeys')
    op.drop_table('e2e_one_time_prekeys')
    op.drop_index(op.f('ix_e2e_link_requests_user_id'), table_name='e2e_link_requests')
    op.drop_index(op.f('ix_e2e_link_requests_code'), table_name='e2e_link_requests')
    op.drop_table('e2e_link_requests')
    op.drop_index(op.f('ix_e2e_devices_user_id'), table_name='e2e_devices')
    op.drop_table('e2e_devices')
    op.drop_table('e2e_device_lists')
    # ### end Alembic commands ###
